### ISSUE TITLE
Hello, will guard input be implemented?

### ISSUE THREAD

**Issue by mrranger** [hempflower/SteamHelper#1]
Hello, will guard input be implemented?

**Comment by hempflower** [comment]
Hello, what type of guard input do you need? Could you give an example?

**Comment by mrranger** [comment]
Sorry for my English, I use Google translator, I saw different projects that are launched in Avast/sandboxie, on github they do not have automatic login to Steam, that is, filling out a login: password and guard, I made my own project but it only works on Steam, not I know how to interact with Sandboxie, will you have such an implementation in future updates?

Example projects:
https://github.com/TheCrowStudios/SteamGamePanel2
https://github.com/IDKTHISSS/JCorePanel

**Comment by hempflower** [comment]
Sorry, there are currently no plans to implement this.
